name: Hello World
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-cb-ga-runner-ec2-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
